version: "2"
services:
  server:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "movemate"
  redis:
    image: redis
    ports: 
      - "6379:6379"
